#Determines whether the player will be invincible when there is an Obsidian monolith, Default: true
player_invincible = true
#Enable player ambient sound, Default: true
player_ambient_sound = true
#Sets the damage percentage Hellfire deals each time，Default: 0.0444
hellfire_damage_amount = 5.0E-4
#Sets the damage percentage Hellcloud deals each time，Default: 0.001
hellcloud_damage_amount = 1.0E-4
#Sets the apollyon's health，Default: 666
apollyon_health = 6666.6
#Limit the amount of damage Apollyon takes each time. Default: 20.0
apollyon_hurt_limit = 666.0
#The probability of summoning Apollyon during the ritual of summoning an apostle (Chance: 1 / value),
#Range: > 1
summon_apollyon_random_value = 10

