#Whether to enable "player cannot attack during attack cooldown"
banAttackWhenCooldown = false
#Whether to enable "player still could have food when full"
couldHaveFoodWhenFull = false
#Whether to enable "refill the item after used or placed"
enableAutoRefill = false
#Whether to enable "protect the farmland when player jumping"
enableFarmlandProtection = true
#The ticks that allowing players to sleep earlier (20Ticks = 1Second)
#Range: 0 ~ 6000
sleepingAdvanceTime = 1200
#Whether to enable "increase the max stack size to 64 for snowball, egg, ender pearl, honey bottle, banners and armor stand"
increaseMaxStackSizeTo64 = true
#Whether to enable "increase the max stack size to 16 for enchanted books"
increaseMaxStackSizeForEnchantedBooks = true
#Whether to enable "increase the max stack size to 16 for potions"
increaseMaxStackSizeForPotions = true
#Whether to enable "increase the max stack size to 16 for saddles, boats, minecarts, beds"
increaseMaxStackSizeForOthers = true
#The prefix word of tooltips
tooltipPrefixWord = "â—† "
#Whether to show the durability info
showDurability = true
#Whether to show the harvest level info
showHarvestLevel = true
#The display type of durability info
#Allowed Values: Number, Symbol5, Symbol10
durabilityTooltipType = "Number"
#Whether to show the tooltips for weapons
showTooltipsForWeapons = false
#Whether to show the tooltips for armors
showTooltipsForArmors = false
#Whether to show the attributes tooltips for foods
showAttributesForFoods = false
#Whether to show the effects tooltips for foods
showEffectsForFoods = true
#Whether to remove the vanilla tooltips
removeVanillaTooltips = false
#A blacklist used to specify the items which not required durability info
#For example: "minecraft:wooden_sword, diamond_sword, @tconstruct"
durabilityBlacklist = "@tconstruct"
#A blacklist used to specify the items which not required weapons tooltips
#For example: "minecraft:wooden_sword, diamond_sword, @tconstruct"
weaponsTooltipsBlacklist = ""
#A blacklist used to specify the items which not required armors tooltips
#For example: "minecraft:iron_chestplate, diamond_chestplate, @tconstruct"
armorsTooltipsBlacklist = ""
#Whether to show the burn time tooltips for fuel
showBurnTimeForFuel = true

