#Which ammo is used by each type of gun.
#Reload type supported.
#Format: "pistol, tacz:9mm" — this means that all guns of the type pistol will use the 9mm.
#"pistol, $minecraft:gold_nugget" - use $ to make the guns use item as ammo.
#"#forge:gun, tacz:9mm" - When the Tag Editor mod is installed, you can use tags to categorize firearms.
#
"Ammo of Gun" = ["pistol, tacz_unidict:pistol", "sniper, tacz_unidict:sniper", "rifle, tacz_unidict:rifle", "shotgun, tacz_unidict:shot", "smg, tacz_unidict:pistol", "rpg, tacz_unidict:barrel", "mg, tacz_unidict:rifle", "fuel, tacz_unidict:fuel_tank"]
#Which guns are not affected by this mod.
"Gun WhiteList" = []
#Guns that use these types of ammo will not be affected by this mod.
"Ammo WhiteList" = []

["Compat: Tag Editor"]
	#Replace TACZ items in loot tables.
	#Format: forge:need_to_replace, minecraft:diamond — this means all items with the tag forge:need_to_replace will be replaced with diamonds.
	#You can also use gunID, ammoID, or attachmentID directly.
	"LootTable Replace" = []
	#Should all TACZ items with the tag tacz:recipe_remove have their recipes removed? (Only effective for TACZ’s default crafting recipes)
	"Recipe Remove" = true

