
[server]
	spawnDemon = false

	[server.mobs]

		[server.mobs.gun_knight]
			#If 'true' disable frontal attack
			"nullify a frontal attack" = true
			#Set damage limit percentage (based on max health)
			#Range: 0.01 ~ 1.0
			"damage limit percentage" = 0.25

			[server.mobs.gun_knight.attribute_config]
				#Regulate mob health by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Health multiplier" = 5.0
				#Regulate mob attack damage by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Attack multiplier" = 3.0

			[server.mobs.gun_knight.neutral_protection_config]
				#Can take unsourced damage without an attack target
				"can damage" = true
				#How far of sourced damage can be ignored when there is no target to attack
				#Range: 0.0 ~ 1.7976931348623157E308
				"can damage distance" = 16.0

			[server.mobs.gun_knight.bossbar]
				#Enable custom bossbar
				"Enable or not" = true

			#Regulate spawning structure
			[server.mobs.gun_knight.structure_generation_config]
				#Maximum height for generation placement. -65 to ignore
				#Range: -65.0 ~ 256.0
				height_max = 100.0
				#Minimum height for generation placement. -65 to ignore
				#Range: -65.0 ~ 256.0
				height_min = 50.0

			#Regulate mob spawning
			[server.mobs.gun_knight.spawn_config]
				#Regulate spawn rate, 0 to disable spawning
				#Range: > 0
				spawn_rate = 1

		[server.mobs.patriot]
			#If 'true' disable frontal attack
			"nullify a frontal attack" = true
			#Set damage limit percentage (based on max health)
			#Range: 0.01 ~ 1.0
			"damage limit percentage" = 0.25

			[server.mobs.patriot.attribute_config]
				#Regulate mob health by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Health multiplier" = 5.0
				#Regulate mob attack damage by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Attack multiplier" = 3.0

			[server.mobs.patriot.partner_attribute_config]
				#Regulate partner mob health by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Health multiplier" = 5.0
				#Regulate partner mob attack damage by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Attack multiplier" = 3.0

			[server.mobs.patriot.bossbar]
				#Enable custom bossbar
				"Enable or not" = true

			[server.mobs.patriot.neutral_protection_config]
				#Can take unsourced damage without an attack target
				"can damage" = true
				#How far of sourced damage can be ignored when there is no target to attack
				#Range: 0.0 ~ 1.7976931348623157E308
				"can damage distance" = 16.0

			#Regulate mob spawning
			[server.mobs.patriot.spawn_config]
				#Regulate spawn rate, 0 to disable spawning
				#Range: > 0
				spawn_rate = 1

		[server.mobs.red]
			#Set damage limit percentage (based on max health)
			#Range: 0.01 ~ 1.0
			"damage limit percentage" = 0.25

			[server.mobs.red.attribute_config]
				#Regulate mob health by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Health multiplier" = 5.0
				#Regulate mob attack damage by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Attack multiplier" = 3.0

			[server.mobs.red.bossbar]
				#Enable custom bossbar
				"Enable or not" = true

			#Regulate mob spawning
			[server.mobs.red.spawn_config]
				#Regulate spawn rate, 0 to disable spawning
				#Range: > 0
				spawn_rate = 1

		[server.mobs.patrol_captain]

			#Regulate mob spawning
			[server.mobs.patrol_captain.spawn_config]
				#Regulate spawn rate, 0 to disable spawning
				#Range: > 0
				spawn_rate = 1

		[server.mobs.mangler]

			#Regulate mob spawning
			[server.mobs.mangler.spawn_config]
				#Regulate spawn rate, 0 to disable spawning
				#Range: > 0
				spawn_rate = 1

		[server.mobs.burdenbeast]

			#Regulate mob spawning
			[server.mobs.burdenbeast.spawn_config]
				#Regulate spawn rate, 0 to disable spawning
				#Range: > 0
				spawn_rate = 1

		[server.mobs.frost_nova]
			#Set damage limit percentage (based on max health)
			#Range: 0.01 ~ 1.0
			"damage limit percentage" = 0.25

			[server.mobs.frost_nova.attribute_config]
				#Regulate mob health by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Health multiplier" = 5.0
				#Regulate mob attack damage by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Attack multiplier" = 3.0

			[server.mobs.frost_nova.partner_attribute_config]
				#Regulate partner mob health by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Health multiplier" = 5.0
				#Regulate partner mob attack damage by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Attack multiplier" = 3.0

			[server.mobs.frost_nova.neutral_protection_config]
				#Can take unsourced damage without an attack target
				"can damage" = true
				#How far of sourced damage can be ignored when there is no target to attack
				#Range: 0.0 ~ 1.7976931348623157E308
				"can damage distance" = 16.0

			[server.mobs.frost_nova.bossbar]
				#Enable custom bossbar
				"Enable or not" = true

			#Regulate mob spawning
			[server.mobs.frost_nova.spawn_config]
				#Regulate spawn rate, 0 to disable spawning
				#Range: > 0
				spawn_rate = 1

		[server.mobs.rosmontis]
			#Set damage limit percentage (based on max health)
			#Range: 0.01 ~ 1.0
			"damage limit percentage" = 0.25

			[server.mobs.rosmontis.attribute_config]
				#Regulate mob health by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Health multiplier" = 5.0
				#Regulate mob attack damage by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Attack multiplier" = 3.0

			[server.mobs.rosmontis.partner_attribute_config]
				#Regulate partner mob health by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Health multiplier" = 5.0
				#Regulate partner mob attack damage by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Attack multiplier" = 3.0

			[server.mobs.rosmontis.neutral_protection_config]
				#Can take unsourced damage without an attack target
				"can damage" = true
				#How far of sourced damage can be ignored when there is no target to attack
				#Range: 0.0 ~ 1.7976931348623157E308
				"can damage distance" = 16.0

			[server.mobs.rosmontis.bossbar]
				#Enable custom bossbar
				"Enable or not" = true

			#Regulate mob spawning
			[server.mobs.rosmontis.spawn_config]
				#Regulate spawn rate, 0 to disable spawning
				#Range: > 0
				spawn_rate = 1

		[server.mobs.pursuer]
			#Set damage limit percentage (based on max health)
			#Range: 0.01 ~ 1.0
			"damage limit percentage" = 0.25

			[server.mobs.pursuer.attribute_config]
				#Regulate mob health by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Health multiplier" = 5.0
				#Regulate mob attack damage by this value
				#Range: 0.0 ~ 1.7976931348623157E308
				"Attack multiplier" = 3.0

			[server.mobs.pursuer.bossbar]
				#Enable custom bossbar
				"Enable or not" = true

			#Regulate mob spawning
			[server.mobs.pursuer.spawn_config]
				#Regulate spawn rate, 0 to disable spawning
				#Range: > 0
				spawn_rate = 1

	[server.tools]

		[server.tools.halberd]
			#tool attack damage
			#Range: 0.0 ~ 1.7976931348623157E308
			attack_damage = 60.0
			#skill 1 numerical requirements
			#Range: 0 ~ 100
			requirements_1 = 10
			#skill 2 numerical requirements
			#Range: 0 ~ 100
			requirements_2 = 50

		[server.tools.shield]
			#skill 1 numerical requirements
			#Range: 0 ~ 100
			requirements_1 = 10

		[server.tools.scratch]
			#skill 1 numerical requirements
			#Range: 0 ~ 100
			requirements_1 = 60

		[server.tools.winter_pass]
			#tool attack damage
			#Range: 0.0 ~ 1.7976931348623157E308
			attack_damage = 18.0
			#skill1 numerical requirements
			#Range: 0 ~ 100
			requirements1 = 50

		[server.tools.ice_broadsword]
			#tool attack damage
			#Range: 0.0 ~ 1.7976931348623157E308
			attack_damage = 30.0
			#skill 1 numerical requirements
			#Range: 0 ~ 100
			requirements_1 = 35

		[server.tools.fire_steel]
			#tool attack damage
			#Range: 0.0 ~ 1.7976931348623157E308
			attack_damage = 24.0

		[server.tools.sankta_ring]
			#skill 1 numerical requirements
			#Range: 0 ~ 100
			requirements_1 = 5

		[server.tools.phantom_grasp]
			#tool attack damage
			#Range: 0.0 ~ 1.7976931348623157E308
			attack_damage = 12.0
			#skill1 numerical requirements
			#Range: 0 ~ 100
			requirements1 = 20

		[server.tools.sacred_halberd]
			#tool attack damage
			#Range: 0.0 ~ 1.7976931348623157E308
			attack_damage = 72.0
			#skill light numerical requirements
			#Range: 0 ~ 100
			light_requirements = 10
			#skill wind numerical requirements
			#Range: 0 ~ 100
			wind_requirements = 70

		[server.tools.sacred_gun]
			#tool attack damage
			#Range: 0.0 ~ 1.7976931348623157E308
			attack_damage = 30.0
			#skill numerical requirements
			#Range: 0 ~ 100
			requirements = 60

		[server.tools.machete]
			#tool attack damage
			#Range: 0.0 ~ 1.7976931348623157E308
			attack_damage = 42.0
			#skill numerical requirements
			#Range: 0 ~ 100
			requirements = 45

	[server.global_setting]
		#Whether living can talk
		"Enable living can talk" = true
		#Whether attack living when dialogue
		"Enable attack living when dialogue" = true
		#The number of times a player can summon a boss each day
		#Range: > 0
		"Can summon number" = 1
		#Whether boss show healthBar
		"Enable bossBar can show" = true

		#Regulate spawning structure
		[server.global_setting.structure_generation_config]
			#Maximum height for generation placement. -65 to ignore
			#Range: -65.0 ~ 256.0
			height_max = 150.0
			#Minimum height for generation placement. -65 to ignore
			#Range: -65.0 ~ 256.0
			height_min = 20.0

	[server.story_setting]
		#Do you need to have seen rosmontis before you can summon she by the Preparation Op
		"false represents being able to summon without seeing" = false

