
["Blessing Scroll"]
	#Damage increase provided by Scroll of a Blessing for each lucky point, as percentage.
	#Range: 0.0 ~ 32768.0
	DamageBoost = 4.0
	#AttackSpeed increase provided by Scroll of a Blessing for each lucky point, as percentage.
	#Range: 0.0 ~ 32768.0
	AttackSpeedBoost = 6.0
	#Dodge increase provided by Scroll of a Blessing for each lucky point, as percentage.
	#Range: 0.0 ~ 100.0
	DodgeBoost = 2.0
	#Max Dodge provided by Scroll of a Blessing, as percentage.
	#Range: 0.0 ~ 100.0
	MaxDodge = 100.0

["THe Needle"]
	#The armor penetration attribute value provided by The Needle, default:0.7
	#Range: 0.0 ~ 1.0
	needleArmorPenetration = 0.7
	#The enchantment piercing attribute value provided by The Needle, default:0.5
	#Range: 0.0 ~ 1.0
	needleEnchantmentPiercing = 0.5
	#The minimum attribute value that the player will increase after using The Needle, default:0.0666
	#Range: 0.0 ~ 1.0
	needleMinimumAttributeEnhancement = 0.1
	#The maximum attribute value that the player will increase after using The Needle, default:0.0666
	#Range: 0.0 ~ 1.0
	needleMaximumAttributeEnhancement = 0.15
	#The preciousness weight of the permanently augmented attributes provided by The Needle(default AttackDamage:0.12, MaxHealth:0.12, AttackSpeed:0.4, Resistance:3.5
	needleAttributeWeight = [0.12, 0.12, 0.4, 3.5]

["Dimensional Will"]
	#The resistance of damage provided by Dimensional Will, as percentage.
	#Range: 0 ~ 100
	DamageResistance = 70
	#The chance of escaping from death provided by Dimensional Will, as percentage.
	#Range: 0 ~ 100
	DeathEscape = 50

["Eternal Watch"]
	#The time(in seconds) that The Eternal Watch can freeze.
	#Range: 0 ~ 32768
	FreezingTime = 15
	#The cooldown of Eternal Watch after frozen the time.
	#Range: 0 ~ 32768
	Cooldown = 60
	#if true, the cooldowns of the eternal watch can can be reduced by other items
	canCooldownsBeReduced = true

["Apocalyptium Armor"]

	["Apocalyptium Armor".Chestplate]
		#display player's apostle title when equipped the apocalyptium chestplate
		displayTitle = true

["Amulet of Slime"]
	#The skill cooldown of the amulet of slime, default 2.5(in seconds).
	#Range: 0.0 ~ 32.0
	cooldown = 2.5

["Gold Feather"]
	#Speed multiplier when using items (relative to original state), default 4.0.
	#Range: 1.0 ~ 32.0
	speedMultiplier = 8.0

["Soul of Obsidian"]
	#The added value of Soul Stealing Attribute, default 5(in percent).
	#Range: 0.0 ~ 32767.0
	soulStealing = 10.0
	#The added value of Soul Decrease Efficiency Attribute, default 5(in percent).
	#Range: 0.0 ~ 32767.0
	soulDecreaseEfficiency = 15.0
	#Defined the increase in probability of special death loot from some creatures for this charm, default 25(in percent).
	#Range: 0.0 ~ 100.0
	specialLootPercentIncrease = 50.0

