
[creativeModeTabs]
	enableCreativeModeTabs = true
	syncSelectedCreativeModeTab = true
	enableBerryTheme = false
	disabledCreativeModeTabs = ["minecraft:op_blocks"]

[stackGroups]
	enableStackGroups = true

